image: docker:git

services: 
  - docker:dind

variables:
  IMAGE_NAME: chimbosonic/hagrid

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"

stages:
  - Build
  - Release

Build image:
  stage: Build
  only:
    changes:
      - Dockerfile
      - scripts/**
  script:
    - docker build -t $IMAGE_NAME -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker image ls
    - docker push $IMAGE_NAME

Release image:
  stage: Release
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - scripts/**  
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker $IMAGE_NAME:latest
