image: docker:git
services: 
  - docker:dind
variables:
  LATEST_VER: chimbosonic/hagrid:latest
  COMMIT_VER: chimbosonic/hagrid:$CI_COMMIT_SHORT_SHA
stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  only:
  - master
  script:
  - docker info
  - docker build -t $LATEST_VER -t $COMMIT_VER .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $LATEST_VER
  - docker push $COMMIT_VER
